
# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:

  build:
    branches:
      only:
        - master
    working_directory: ~/var/www
    docker:
      - image: brettt89/silverstripe-web
    steps:
      - checkout
      # Download and cache composer dependencies
      - restore_cache:
          keys:
            - v1-composer-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-composer-
      - run:
          name: Install Composer + run
          command: |
            curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
            composer install --prefer-source --no-interaction
            composer vendor-expose copy
      - save_cache:
          paths:
            - ./vendor
          key: v1-composer-{{ checksum "composer.json" }}
      - persist_to_workspace:
          root: ~/var/
          paths: www

  test:
    working_directory: ~/var/www
    docker:
      - image: brettt89/silverstripe-web
        environment:
          - SS_DATABASE_CLASS=MySQLPDODatabase
          - SS_DATABASE_SERVER=127.0.0.1
          - SS_DATABASE_USERNAME=root
          - SS_DATABASE_PASSWORD=ubuntu
          - SS_DATABASE_NAME=circle_test
          - SS_ENVIRONMENT_TYPE=dev
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_USER=root
          - MYSQL_ROOT_PASSWORD=ubuntu
          - MYSQL_DATABASE=circle_test
          - MYSQL_HOST=127.0.0.1
    steps:
      - attach_workspace:
        at: ~/var/
      - run: vendor/silverstripe/framework/sake dev/build
      - run: vendor/bin/phpunit mysite

  package:
    working_directory: ~/var/www
    docker:
      - image: brettt89/silverstripe-web
    steps:
      - attach_workspace:
          at: ~/var/
      - run: ls -la

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - package:
          requires:
            - test


